import React from 'react';
import type { ReactElement } from 'react';
import { render } from '@testing-library/react';

import { HoneyStyleProvider } from '../../../providers';
import { themeMock } from '../../../__mocks__';
import { styled } from '../../../styled';

const customRender = (element: ReactElement) =>
  render(<HoneyStyleProvider theme={themeMock}>{element}</HoneyStyleProvider>);

/**
 * Returns the full CSS text generated by Honey styled-components.
 *
 * Media query styles are not applied directly in JSDOM,
 * so we assert against the injected <style> output instead.
 */
const getRenderedCssText = (): string =>
  Array.from(document.querySelectorAll('style'))
    .map(tag => tag.textContent ?? '')
    .join('\n');

describe('@honey-media CSS at-rule', () => {
  it('should ignore @honey-media when no arguments are provided', () => {
    const Box = styled('div')`
      @honey-media;
    `;

    const { getByTestId } = customRender(<Box data-testid="media" />);

    expect(getByTestId('media')).toBeInTheDocument();
  });

  it('should not generate CSS when @honey-media block is empty', () => {
    const Box = styled('div')`
      @honey-media (sm:up) {
      }
    `;

    customRender(<Box data-testid="media" />);

    const cssText = getRenderedCssText();

    expect(cssText).not.toContain('@honey-media');
    expect(cssText).not.toContain('@media');
  });

  it('should apply styles inside @honey-media(sm:up)', () => {
    const Box = styled('div')`
      color: black;

      @honey-media (sm:up) {
        color: red;
      }
    `;

    const { getByTestId } = customRender(<Box data-testid="media" />);

    expect(getByTestId('media')).toHaveStyle({
      color: 'black',
    });

    const cssText = getRenderedCssText();

    expect(cssText).toContain('@media screen and (min-width: 768px)');
    expect(cssText).toContain('color:red');
  });

  it('should apply styles inside @honey-media(sm:down)', () => {
    const Box = styled('div')`
      @honey-media (sm:down) {
        padding: 12px;
      }
    `;

    customRender(<Box data-testid="media" />);

    const cssText = getRenderedCssText();

    expect(cssText).toContain('@media screen and (max-width: 768px)');
    expect(cssText).toContain('padding:12px');
  });

  it('should support multiple breakpoint rules in @honey-media(sm:up md:down)', () => {
    const Box = styled('div')`
      @honey-media (sm:up md:down) {
        font-size: 20px;
      }
    `;

    customRender(<Box data-testid="media" />);

    const cssText = getRenderedCssText();

    expect(cssText).toContain('@media');
    expect(cssText).toContain('(min-width: 768px)');
    expect(cssText).toContain('(max-width: 992px)');
    expect(cssText).toContain('font-size:20px');
  });

  it('should support orientation tokens inside @honey-media', () => {
    const Box = styled('div')`
      @honey-media (sm:up landscape) {
        background: blue;
      }
    `;

    customRender(<Box data-testid="media" />);

    const cssText = getRenderedCssText();

    expect(cssText).toContain('(min-width: 768px)');
    expect(cssText).toContain('(orientation: landscape)');
    expect(cssText).toContain('background:blue');
  });

  it('should support media type tokens inside @honey-media(print)', () => {
    const Box = styled('div')`
      @honey-media (print sm:up) {
        display: none;
      }
    `;

    customRender(<Box data-testid="media" />);

    const cssText = getRenderedCssText();

    expect(cssText).toContain('@media print');
    expect(cssText).toContain('(min-width: 768px)');
    expect(cssText).toContain('display:none');
  });

  it('should not apply styles when using unknown breakpoint token', () => {
    const Box = styled('div')`
      @honey-media (xxl:up) {
        color: green;
      }
    `;

    customRender(<Box data-testid="media" />);

    const cssText = getRenderedCssText();

    expect(cssText).not.toContain('@media');
    expect(cssText).toBe('');
  });

  it('should transform nested @honey-media directives correctly', () => {
    const Box = styled('div')`
      @honey-media (sm:up) {
        .child {
          padding: 16px;

          @honey-media (md:down) {
            padding: 8px;
          }
        }
      }
    `;

    customRender(
      <Box data-testid="media">
        <div className="child" data-testid="child" />
      </Box>,
    );

    const cssText = getRenderedCssText();

    expect(cssText).toContain('(min-width: 768px)');
    expect(cssText).toContain('(max-width: 992px)');
    expect(cssText).toContain('padding:8px');
  });

  it('should support multiple @honey-media blocks at the same selector level', () => {
    const Box = styled('div')`
      font-size: 16px;

      @honey-media (md:down) {
        font-size: 14px;
      }

      @honey-media (sm:down) {
        font-size: 12px;
        font-weight: 700;
      }
    `;

    customRender(<Box data-testid="media" />);

    const cssText = getRenderedCssText();

    // Base style must remain
    expect(cssText).toContain('font-size:16px');

    // First media block: md:down
    expect(cssText).toContain('@media screen and (max-width: 992px)');
    expect(cssText).toContain('font-size:14px');

    // Second media block: sm:down
    expect(cssText).toContain('@media screen and (max-width: 768px)');
    expect(cssText).toContain('font-size:12px');
    expect(cssText).toContain('font-weight:700');
  });

  it('should merge &: pseudo selectors correctly inside @honey-media block', () => {
    const Box = styled('div')`
      @honey-media (xs:down) {
        &:hover {
          opacity: 0.5;
        }
      }
    `;

    customRender(<Box data-testid="media" />);

    const cssText = getRenderedCssText();

    expect(cssText).toContain('@media');

    // Must NOT introduce descendant selectors like ".class :hover"
    expect(cssText).not.toMatch(/\.hscn-[a-z0-9]+\s+:/);
    expect(cssText).toMatch(/\.hscn-[a-z0-9]+:hover/);
    expect(cssText).toContain('opacity:0.5');
  });

  it('should support child combinator selector and declarations inside @honey-media block', () => {
    const Box = styled('div')`
      @honey-media (sm:down) {
        background-color: green;

        > .content {
          width: 100%;
        }
      }
    `;

    customRender(
      <Box data-testid="media">
        <div className="content" data-testid="content" />
      </Box>,
    );

    const cssText = getRenderedCssText();

    expect(cssText).toContain('@media screen and (max-width: 768px)');
    // Parent-level declaration must be applied inside media
    expect(cssText).toContain('background-color:green');
    // Selector must be correctly expanded with parent + combinator
    expect(cssText).toMatch(/\.hscn-[a-z0-9]+\s*>\s*\.content/);
    expect(cssText).toContain('width:100%');
  });
});
